[package]
name = "varpro"
version = "0.0.0"
authors = ["geo-ant"]
edition = "2018"
license = "MIT"
homepage = "https://github.com/geo-ant/varpro"
repository = "https://github.com/geo-ant/varpro"
description = "An easy to use least-squares fitter, that uses the Variable Projection algorithm to fit nonlinear models which can be written as a linear combination of nonlinear model functions."
readme = "README.md"
categories = ["mathematics","science","algorithms"]
keywords = ["nonlinear","least","squares","fitting","regression"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
snafu = "0.6"
levenberg-marquardt = "0.7"
nalgebra = "0.24"
num-traits = "0.2"

[package.metadata.docs.rs]
# To build locally use
#   RUSTDOCFLAGS="--html-in-header katex-header.html" cargo doc --no-deps --document-private-items --open
rustdoc-args = [ "--html-in-header", "katex-header.html" ]