[package]
name = "shared_test_code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
varpro = {path = "../varpro"}
nalgebra = "0.32"
num-traits = "0.2"
